#!/bin/bash

TCR_HOME="${TCR_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
TCR_WORK_DIRECTORY="$(pwd)"

source "$TCR_HOME/lib/lock_file.sh"
source "$TCR_HOME/lib/tcr/error_consts.sh"
source "$TCR_HOME/lib/tcr/action_consts.sh"

tcr() {
    local action="$1"

    case "$action" in
        "$TCR_ACTION_ENABLE")
            enable_tcr
        ;;
        "$TCR_ACTION_DISABLE")
            disable_tcr
        ;;
        *)
            raise_error "$TCR_ERROR_TCR_UNKNOWN_ACTION"
        ;;
    esac
}

# -- Actions -- #

enable_tcr() {
    if is_lock_file_existing; then
        raise_error "$TCR_ERROR_TCR_ALREADY_ENABLED"
        return
    fi

    setup_lock_file
    print_status 'ON'
}

disable_tcr() {
    remove_lock_file
    print_status 'OFF'
}

# -- Guts -- #

prepare_lock_file_content() {
    local content="TCR_WORK_DIRECTORY=$TCR_WORK_DIRECTORY"

    echo "$content"
}

setup_lock_file() {
    create_lock_file
    lock_file_set_content "$(prepare_lock_file_content)"
}

# -- Main -- #

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    tcr "$@"
fi