# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'fileutils'
require_relative 'lib/cd_steps'

scheme = 'One Times One'

ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '60'

opt_out_usage
default_platform(:ios)

platform :ios do
  before_all do
    set_xcode_version
  end

  lane :dev_stage do
    dev_build
    dev_test
  end

  lane :acc_stage do
    stage = CD_STAGES[:ACC]

    build_for_testing(stage: stage,
                      scheme: scheme)
    test_without_building(stage: stage,
                          scheme: scheme,
                          test_plan: 'AcceptanceTests')
  end

  lane :app_store_screenshots do
    capture_store_screenshots(devices: ['iPhone 16 Pro Max'],
                              languages: %w[en-US de-DE],
                              scheme: 'AppStoreScreenshots',
                              test_plan: 'AppStoreScreenshots',
                              output_directory: './Release Artifacts/screenshots',
                              clear_previous_screenshots: true)
  end

  lane :dev_build do
    build_for_testing(stage: CD_STAGES[:DEV],
                      scheme: scheme)
  end

  lane :dev_test do
    test_without_building(stage: CD_STAGES[:DEV],
                          scheme: scheme,
                          test_plan: 'DevelopmentTests')
  end

  lane :dev_clean do
    clean_build_artifacts(stage: CD_STAGES[:DEV])
  end
end
