# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'lib/cd_steps'

scheme = 'One Times One'

ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '60'

opt_out_usage
default_platform(:ios)

platform :ios do
  before_each do
    set_xcode_version
  end

  lane :dev_stage do
    stage = CD_STAGES[:DEV]

    build_for_testing(stage: stage,
                      scheme: scheme)
    test_without_building(stage: stage,
                          scheme: scheme,
                          test_plan: 'DevelopmentTests')
  end

  lane :acc_stage do
    stage = CD_STAGES[:ACC]

    build_for_testing(stage: stage,
                      scheme: scheme)
    test_without_building(stage: stage,
                          scheme: scheme,
                          test_plan: 'AcceptanceTests')
  end

  lane :app_store_screenshots do
    devices = ['iPhone 16 Pro Max']
    languages = %w[en-US de-DE]
    stage = 'store_snapshot'
    scheme = 'AppStoreScreenshots'
    testplan = 'AppStoreScreenshots'
    output_directory = './Release Artifacts/screenshots'
    clear_previous_screenshots = true

    status_bar_settings = [
      '--dataNetwork wifi',
      '--wifiMode active',
      '--wifiBars 3',
      '--cellularMode active',
      "--operatorName ''",
      '--cellularBars 4',
      '--batteryState charged',
      '--batteryLevel 100',
      '--time 2007-01-09T09:41:00.000+01:00Z' # The time set by fastlane by default is not a value IOS date/time string. it is missing the '.000' part after the seconds
    ].join(' ')

    testing_build_paths = CDArtifactPaths.new(stage, 'store_snapshot_result')

    build_for_testing(stage: stage,
                      scheme: scheme)

    capture_screenshots(devices: devices,
                        languages: languages,
                        scheme: scheme,
                        testplan: testplan,
                        test_without_building: true,
                        clear_previous_screenshots: clear_previous_screenshots,
                        override_status_bar: true,
                        override_status_bar_arguments: status_bar_settings,
                        disable_package_automatic_updates: true,
                        skip_package_dependencies_resolution: true,
                        xcargs: '-quiet',
                        output_directory: output_directory,
                        derived_data_path: testing_build_paths.derived_data_path,
                        cloned_source_packages_path: testing_build_paths.cloned_source_packages_path,
                        buildlog_path: testing_build_paths.buildlog_path,
                        result_bundle: true,
                        namespace_log_files: true,
                        headless: true,
                        concurrent_simulators: false,
                        stop_after_first_error: true,
                        skip_open_summary: true)
  end
end
