# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Accepance Stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  accepance-tests:
    name: iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo xcode-select -s /Applications/Xcode_16.app
    - run: xcodebuild build-for-testing -scheme "Basic Multiplication" -testPlan AcceptanceTests -destination "platform=iOS Simulator,name=iPhone 16 Pro"
    - run: xcodebuild test-without-building -scheme "Basic Multiplication" -testPlan AcceptanceTests -destination "platform=iOS Simulator,name=iPhone 16 Pro"
