name: 'XCPipleine'

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  development-tests:
    name: Development Stage
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build for testing
      run: ./CDPipeline/dev_stage/build_for_testing.sh ./CDPipeline/dev_stage/.env
    - name: Run development tests
      run: ./CDPipeline/dev_stage/run_dev_tests.sh ./CDPipeline/dev_stage/.env
  acceptance-tests:
    name: Acceptance Stage
    runs-on: macos-latest
    needs: development-tests
    if: needs.development-tests.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: './CDPipeline'
          bundler-cache: true
      - name: Build for testing
        run: ./CDPipeline/dev_stage/build_for_testing.sh ./CDPipeline/dev_stage/.env
      - name: Run acceptance tests
        run: ./CDPipeline/acc_stage/run_acceptance_tests.sh ./CDPipeline/dev_stage/.env
  create-staged-rc:
    name: Deployment Stage
    runs-on: macos-latest
    needs: acceptance-tests
    if: needs.acceptance-tests.result == 'success'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: './CDPipeline'
        bundler-cache: true
    - name: Tag staged RC
      run: ./CDPipeline/dev_stage/tag_staged_rc.sh
