name: 'Development Stage'

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  development-tests:
    name: Development Tests
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build for testing
      run: ./CDPipeline/dev_stage/build_for_testing.sh ./CDPipeline/dev_stage/.env
    - name: Run development tests
      run: ./CDPipeline/dev_stage/run_dev_tests.sh ./CDPipeline/dev_stage/.env
    - name: Collect artifacts
      run: ./CDPipeline/dev_stage/collect_artifacts.sh ./CDPipeline/dev_stage/.env
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: './CDPipeline'
        bundler-cache: true
    - name: Tag staged RC
      run: ./CDPipeline/dev_stage/tag_staged_rc.sh
