# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: DevelopmentTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcode-select -s /Applications/Xcode_16.app
    - run: xcodebuild build-for-testing -scheme DevelopmentTests -destination "platform=iOS Simulator,name=iPhone 16 Pro"
    - run: xcodebuild test-without-building -scheme DevelopmentTests -destination "platform=iOS Simulator,name=iPhone 16 Pro"
