name: JABOS Pipeline Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  development-stage:
    name: Development Stage
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install project tools
      run: ./Tools/install_tools.sh
    - name: Run tests
      working-directory: ./CDPipeline
      run: ../Tools/bin/shellspec/shellspec 